### ISSUE TITLE
Installation problem with css

### ISSUE THREAD

**Issue by chougron** [akeneo/badger#106]
I'm following the installation process on the Readme, but the CSS files are not created. When I launch this function : `nodejs node_modules/gulp/bin/gulp.js less`, nothing is created in the web/css folder.

I tried to give full rights to the files, so it is not a file rights problem.

In the end, I don't have any all.css file, and the design of the website is pretty broken. All the rest seems to be working perfectly otherwise.

**Comment by chougron** [comment]
Actually the code used is the following in gulpfile.js :
```
    return gulp.src('./src/**/Resources/public/css/*.less')
        .pipe(less())
        .pipe(concat('all.css'))
.pipe(gulp.dest('./web/css'));
```
But I checked all the bundles and there are no files corresponding. There are some .css files in `src/GateBundle/Resources/public/css`. It's the only files that could correspond and it's not .less files.

**Comment by grena** [comment]
Hello @chougron !
You're right, the `gulpfile` needs some update, indeed there is not `.less` to compile anymore, I'll open an issue to clean this!

However, the `.css` files in the GateBundle should be moved in you `web` directory. This is done by the command `php app/console assets:install` (in the readme too).

Can I ask you to run it again to test?

**Comment by chougron** [comment]
Yes, the .css files were moved to the web directory.
But there is the file `css/all.css` being called in the admin pages, that doesn't exist.

I also notice that you have a different version of Semantic UI `vendor/semantic-ui-css/*`
The version I have by following the installation process is **2.2.4**, but when I access the files on badger.akeneo.com, the version is **2.1.7**.
Is is causing problems in the administration : The content of the page is behind the menu and the dropdown items appears one row under their parents (making them unable to select, since you hover out of the parent without hovering in the child)

**Comment by grena** [comment]
Heyy you're right, we still use semantic ui for the admin part! I'd like to drop that, kind of "legacy" stuff.
I'll try a brand new install on my side to reproduce this problem, this part needs a clean up :)

**Comment by chougron** [comment]
I pulled the code today with the new changes, and the installation worked fine! Thanks!

**Comment by grena** [comment]
Hell @chougron , yup, I put back the `main.less` file that was missing :)
I'm currently dropping the semantic ui theme on admin side to have the same everywhere ( #107 ) if you're interested.

Have a nice day!
